# Generated by Django 5.1.6 on 2025-02-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={
                "ordering": ["done", "-updated"],
                "verbose_name": "Todo",
                "verbose_name_plural": "Todos",
            },
        ),
    ]
