# Generated by Django 5.1.6 on 2025-02-10 23:11

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0003_alter_todo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="content",
            field=tinymce.models.HTMLField(verbose_name="Content"),
        ),
    ]
