# Generated by Django 5.1.6 on 2025-02-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0004_alter_todo_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="excerpt",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Excerpt"
            ),
        ),
    ]
