# Generated by Django 5.1.6 on 2025-02-11 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0005_todo_excerpt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="excerpt",
        ),
    ]
